import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";

// These styles apply to every route in the application
import "./globals.css";

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--fontBebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${bebasNeue.variable}`}>
      <body>{children}</body>
    </html>
  );
}
